<?php
namespace tutorial;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Calculator_add_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'num1',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'num2',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $num1 = null;
    /**
     * @var int
     */
    public $num2 = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['num1'])) {
                $this->num1 = $vals['num1'];
            }
            if (isset($vals['num2'])) {
                $this->num2 = $vals['num2'];
            }
        }
    }

    public function getName()
    {
        return 'Calculator_add_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->num1);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->num2);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Calculator_add_args');
        if ($this->num1 !== null) {
            $xfer += $output->writeFieldBegin('num1', TType::I32, 1);
            $xfer += $output->writeI32($this->num1);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->num2 !== null) {
            $xfer += $output->writeFieldBegin('num2', TType::I32, 2);
            $xfer += $output->writeI32($this->num2);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
