<?php
namespace tutorial;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface CalculatorIf extends \shared\SharedServiceIf
{
    /**
     */
    public function ping();
    /**
     * @param int $num1
     * @param int $num2
     * @return int
     */
    public function add($num1, $num2);
    /**
     * @param int $logid
     * @param \tutorial\Work $w
     * @return int
     * @throws \tutorial\InvalidOperation
     */
    public function calculate($logid, $w);
    /**
     */
    public function zip();
}
