<?php
namespace tutorial;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class InvalidOperation extends TException
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'whatOp',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'why',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $whatOp = null;
    /**
     * @var string
     */
    public $why = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['whatOp'])) {
                $this->whatOp = $vals['whatOp'];
            }
            if (isset($vals['why'])) {
                $this->why = $vals['why'];
            }
        }
    }

    public function getName()
    {
        return 'InvalidOperation';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->whatOp);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->why);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('InvalidOperation');
        if ($this->whatOp !== null) {
            $xfer += $output->writeFieldBegin('whatOp', TType::I32, 1);
            $xfer += $output->writeI32($this->whatOp);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->why !== null) {
            $xfer += $output->writeFieldBegin('why', TType::STRING, 2);
            $xfer += $output->writeString($this->why);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
